global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'freqtrade-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['freqtrade_exporter:3001']
